### PR TITLE
v1.0.6 Release

### PR DESCRIPTION
**Pull request by eduadiez**

### CODE REVIEW

**Comment by vanjan** [comment]
Can we release with lighthouse 0.2.9? I'm getting terrible attestation rate around 50% with 0.2.5

**Comment by eduadiez** [comment]
Sorry, this repo isn't updated. 
it's already released: http://my.dappnode/#/installer/lighthouse-medalla-beacon-chain.dnp.dappnode.eth

Screenshot 2020-09-17 at 12 59 57

**Comment by vanjan** [comment]
not sure what's going on, but after installing 1.0.5 (0.2.9 upstream) the logs show:

    Sep 17 11:06:07.153 INFO Lighthouse started                      version: Lighthouse/v0.2.4-cc44a64d+

Screenshot 2020-09-17 at 13 05 35

**Comment by eduadiez** [comment]
weird, let me check it

**Comment by eduadiez** [comment]
Fixed! Sorry for the inconvenience

**Pull request closed without merging**
